name: bikesensors
services:
  bikesensors.mqtt:
    container_name: bikesensors.mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./MqttSettings/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./.containers/mqtt:/mosquitto
      - ./.containers/mqtt/data:/mosquitto/data
      - ./.containers/mqtt/log:/mosquitto/log
  bikesensors.api:
    container_name: bikesensors.api 
    image: ${DOCKER_REGISTRY-}bikesensors
    build:
      context: .
      dockerfile: BikeSensors.API/Dockerfile
    ports:
     - 5000:5000
    environment:
     - ASPNETCORE_HTTP_PORTS=5000
    depends_on:
     - bikesensors.mqtt
  bikesensors.mqqtfake:
    container_name: bikesensors.mqqtfake
    build: 
      context: .
      dockerfile: BikeSensors.FakeData/Dockerfile
    environment:
      - BROKER=bikesensors.mqtt
      - HEART_RATE_DELAY=2
      - POWER_DELAY=0.5
    depends_on:
     - bikesensors.mqtt
     - bikesensors.api